In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from urllib.parse import urljoin

In [2]:
url = "https://quotes.toscrape.com/"

print(url)

https://quotes.toscrape.com/

In [3]:
response = requests.get(url)

print(response.status_code)

200

In [4]:
html = response.text

print(html[:1000])

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Quotes to Scrape</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
    <link rel="stylesheet" href="/static/main.css">


</head>
<body>
    <div class="container">
        <div class="row header-box">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>

                    <a href="/login">Login</a>

                </p>
            </div>
        </div>


<div class="row">
    <div class="col-md-8">

    <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”</span>
        <span>by <small class="auth

In [5]:
soup = BeautifulSoup(html, "html.parser")

print(type(soup))

<class 'bs4.BeautifulSoup'>

In [6]:
first_quote = soup.select_one("div.quote")

print(first_quote)

<div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
<span class="text" itemprop="text">“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”</span>
<span>by <small class="author" itemprop="author">Albert Einstein</small>
<a href="/author/Albert-Einstein">(about)</a>
</span>
<div class="tags">
            Tags:
            <meta class="keywords" content="change,deep-thoughts,thinking,world" itemprop="keywords"/>
<a class="tag" href="/tag/change/page/1/">change</a>
<a class="tag" href="/tag/deep-thoughts/page/1/">deep-thoughts</a>
<a class="tag" href="/tag/thinking/page/1/">thinking</a>
<a class="tag" href="/tag/world/page/1/">world</a>
</div>
</div>

In [7]:
quote_text = first_quote.select_one("span.text").get_text(strip=True)

print(quote_text)

“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”

In [8]:
author = first_quote.select_one("small.author").get_text(strip=True)

print(author)

Albert Einstein

In [9]:
tags = first_quote.select("div.tags a.tag")

print(tags)

[<a class="tag" href="/tag/change/page/1/">change</a>, <a class="tag" href="/tag/deep-thoughts/page/1/">deep-thoughts</a>, <a class="tag" href="/tag/thinking/page/1/">thinking</a>, <a class="tag" href="/tag/world/page/1/">world</a>]

In [11]:
author_link = first_quote.select_one("small.author + a")

print(author_link)

<a href="/author/Albert-Einstein">(about)</a>

In [12]:
relative_author_url = author_link.get("href")

print(relative_author_url)

/author/Albert-Einstein

In [14]:
tags = first_quote.select("div.tags a.tag")

print(tags)

[<a class="tag" href="/tag/change/page/1/">change</a>, <a class="tag" href="/tag/deep-thoughts/page/1/">deep-thoughts</a>, <a class="tag" href="/tag/thinking/page/1/">thinking</a>, <a class="tag" href="/tag/world/page/1/">world</a>]

In [15]:
tag_names = [tag.get_text(strip=True) for tag in tags]

print(tag_names)

['change', 'deep-thoughts', 'thinking', 'world']

In [17]:
author_link = first_quote.select_one("small.author + a")

print(author_link)

<a href="/author/Albert-Einstein">(about)</a>

In [18]:
author_url = urljoin(url, relative_author_url)

print(author_url)

https://quotes.toscrape.com/author/Albert-Einstein

In [19]:
first_quote_data = {
    "quote": quote_text,
    "author": author,
    "tags": tag_names,
    "author_url": author_url
}

print(first_quote_data)

{'quote': '“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”', 'author': 'Albert Einstein', 'tags': ['change', 'deep-thoughts', 'thinking', 'world'], 'author_url': 'https://quotes.toscrape.com/author/Albert-Einstein'}

In [20]:
quotes = soup.select("div.quote")

print(len(quotes))

10

In [21]:
rows = []

for quote in quotes:

    quote_text = quote.select_one("span.text").get_text(strip=True)

    author = quote.select_one("small.author").get_text(strip=True)

    tags = quote.select("div.tags a.tag")
    tag_names = [tag.get_text(strip=True) for tag in tags]

    author_link = quote.select_one("small.author + a")
    relative_author_url = author_link.get("href")
    author_url = urljoin(url, relative_author_url)

    row = {
        "quote": quote_text,
        "author": author,
        "tags": tag_names,
        "author_url": author_url
    }

    rows.append(row)

In [22]:
print(len(rows))

10

In [23]:
df = pd.DataFrame(rows)

df.head()

,quote,author,tags,author_url
0,“The world as we have created it is a process ...,Albert Einstein,"[change, deep-thoughts, thinking, world]",https://quotes.toscrape.com/author/Albert-Eins...
1,"“It is our choices, Harry, that show what we t...",J.K. Rowling,"[abilities, choices]",https://quotes.toscrape.com/author/J-K-Rowling
2,“There are only two ways to live your life. On...,Albert Einstein,"[inspirational, life, live, miracle, miracles]",https://quotes.toscrape.com/author/Albert-Eins...
3,"“The person, be it gentleman or lady, who has ...",Jane Austen,"[aliteracy, books, classic, humor]",https://quotes.toscrape.com/author/Jane-Austen
4,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,"[be-yourself, inspirational]",https://quotes.toscrape.com/author/Marilyn-Monroe

In [24]:
df.shape

(10, 4)

In [25]:
quotes = soup.select("div.quote")

print(len(quotes))

10

In [26]:
rows = []

In [27]:
for quote in quotes:

    quote_text = quote.select_one("span.text").get_text(strip=True)

    author = quote.select_one("small.author").get_text(strip=True)

    tags = quote.select("div.tags a.tag")
    tag_names = [tag.get_text(strip=True) for tag in tags]

    author_link = quote.select_one("small.author + a")
    relative_author_url = author_link.get("href")
    author_url = urljoin(url, relative_author_url)

    row = {
        "quote": quote_text,
        "author": author,
        "tags": tag_names,
        "author_url": author_url
    }

    rows.append(row)

In [28]:
print(len(rows))

10

In [29]:
df = pd.DataFrame(rows)

In [30]:
df.head()

,quote,author,tags,author_url
0,“The world as we have created it is a process ...,Albert Einstein,"[change, deep-thoughts, thinking, world]",https://quotes.toscrape.com/author/Albert-Eins...
1,"“It is our choices, Harry, that show what we t...",J.K. Rowling,"[abilities, choices]",https://quotes.toscrape.com/author/J-K-Rowling
2,“There are only two ways to live your life. On...,Albert Einstein,"[inspirational, life, live, miracle, miracles]",https://quotes.toscrape.com/author/Albert-Eins...
3,"“The person, be it gentleman or lady, who has ...",Jane Austen,"[aliteracy, books, classic, humor]",https://quotes.toscrape.com/author/Jane-Austen
4,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,"[be-yourself, inspirational]",https://quotes.toscrape.com/author/Marilyn-Monroe